character_index:
    path:     /
    defaults: { _controller: "AppBundle:Character:index" }
    methods:  GET

character_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Character:show" }
    methods:  GET

character_new:
    path:     /new
    defaults: { _controller: "AppBundle:Character:new" }
    methods:  [GET, POST]

character_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Character:edit" }
    methods:  [GET, POST]

character_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Character:delete" }
    methods:  DELETE
